/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health / hello
         * @description Simple endpoint to verify the API is running.
         */
        get: operations["AppController_getHello_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns a paginated list of users. Admins may filter by type and by a case-insensitive search on name or userName.
         */
        get: operations["UsersController_listUsers_v1"];
        put?: never;
        /**
         * Create a new user
         * @description Create a new user with the given information. Only admin can create users
         */
        post: operations["UsersController_createUser_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Get a user with the given ID
         */
        get: operations["UsersController_getUser_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Update a user with the given information
         */
        patch: operations["UsersController_updateUser_v1"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description Get the current user
         */
        get: operations["UsersController_getCurrentUser_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request API token
         * @description Issues a new JWT for the given user (subject to caller privilege).
         */
        post: operations["ApiTokensController_createApiToken_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create item provider
         * @description Admin creates an item provider for a user account.
         */
        post: operations["ItemProvidersController_createItemProvider_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer funds
         * @description Transfer funds from the authenticated user’s NFC-backed account to a recipient account.
         */
        post: operations["TransactionsController_transfer_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/purchase-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purchase items
         * @description Authenticates with the NFC card and purchases items from a provider account.
         */
        post: operations["TransactionsController_purchaseItem_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accounts
         * @description Returns a paginated list of accounts with each account owner (user) summary. Admins may filter by owner user id, owner user type, lock state, and a case-insensitive search on NFC UID or owner name fields.
         */
        get: operations["AccountsController_listAccounts_v1"];
        put?: never;
        /**
         * Create account
         * @description Creates an NFC-backed account for a user. Requires an admin API token.
         */
        post: operations["AccountsController_createAccount_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List account transactions
         * @description Returns transactions where the account is the payer, payee, or mint recipient. The account owner or an admin may call this.
         */
        get: operations["AccountsController_getAccountTransactions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item-providers/{providerId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List provider items
         * @description Lists items for an item-provider owned by the caller.
         */
        get: operations["ItemsController_listProviderItems_v1"];
        put?: never;
        /**
         * Create provider item
         * @description Creates an item for an item-provider owned by the caller.
         */
        post: operations["ItemsController_createProviderItem_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item-providers/{providerId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get provider item
         * @description Gets one item by id for an item-provider owned by the caller.
         */
        get: operations["ItemsController_getProviderItem_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/mint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint currency
         * @description Increases an account balance and records a mint transaction on the chain.
         */
        post: operations["AdminController_mint_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with the given username and password
         */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description User display name.
             * @example Ada Lovelace
             */
            name: string;
            /** @description User username (letters, digits, - _ + only; no spaces) */
            userName: string;
        };
        CreateUserResponseDto: {
            /** @description User ID */
            id: string;
            /** @description User name */
            name: string;
            /** @description User password */
            password: string;
            /** @description User type */
            type: string;
        };
        ListUserItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
            userName: string;
            /** @enum {string} */
            type: "user" | "provider" | "admin";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ListUsersResponseDto: {
            users: components["schemas"]["ListUserItemDto"][];
            /** @description Total rows matching the filters (ignoring limit/offset). */
            total: number;
        };
        UpdateUserRequestDto: {
            /**
             * @description User display name.
             * @example Ada Lovelace
             */
            name: string;
            /**
             * @description Account password for API login (stored with Argon2id; distinct from the generated card PIN).
             * @example a-long-random-secret
             */
            password: string;
            /**
             * @description User type.
             * @example admin
             * @enum {string}
             */
            type: "user" | "provider" | "admin";
        };
        UpdateUserResponseDto: {
            /** @description User ID */
            id: string;
            /** @description User name */
            name: string;
            /** @description User type */
            type: string;
        };
        UserAccountSummaryDto: {
            /** Format: uuid */
            id: string;
            /** @description NFC card UID when the account is bound to a card. */
            nfcCardUid: Record<string, never> | null;
            /** @description Account public key (hex). */
            publicKeyHex: string;
            /** @description Current balance. */
            balance: number;
            /** @description Whether the account is locked. */
            isLocked: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GetUserResponseDto: {
            /** @description User ID */
            id: string;
            /** @description User name */
            name: string;
            /** @description User type */
            type: string;
            /**
             * Format: uuid
             * @description Item provider id when the user type is provider and an item provider exists.
             */
            providerId?: string;
            /** @description Included when the request uses includeAccounts=true. */
            accounts?: components["schemas"]["UserAccountSummaryDto"][];
        };
        RequestTokenDto: {
            /**
             * Format: uuid
             * @description Target user id.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            userId: string;
            /**
             * @description Requested privilege for the issued token (defaults to user).
             * @example provider
             * @enum {string}
             */
            privilege?: "admin" | "provider" | "user";
        };
        RequestTokenResponseDto: {
            /**
             * @description JWT token.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlclR5cGUiOiJ1c2VyIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
             */
            token: string;
        };
        CreateItemProviderDto: {
            /** @example Main shop counter */
            name: string;
            /**
             * @description The user that owns this provider.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            userId: string;
            /**
             * @description Account to receive funds for this provider. Must belong to userId.
             * @example 9c7bb5eb-1684-49b2-bf1d-7f8ec8f0b6a4
             */
            accountId: string;
        };
        ItemProviderResponseDto: {
            /**
             * Format: uuid
             * @description Item-provider ID
             */
            id: string;
            /** @description Display name */
            name: string;
            /**
             * Format: uuid
             * @description Owning user ID
             */
            userId: string;
            /**
             * Format: uuid
             * @description Linked account ID
             */
            accountId: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
        TransferDto: {
            /**
             * @description NFC card UID (as read from the card reader).
             * @example 04A224B1C83A80
             */
            nfcCardUid: string;
            /**
             * Format: uuid
             * @description Recipient account id (bank, vending machine, or another account).
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            toAccountId: string;
            /**
             * @description Value of the transfer in currency units.
             * @example 2.5
             */
            value: number;
            /**
             * @description Optional purchase description.
             * @example Cafeteria lunch
             */
            description?: string;
            /**
             * @description 4-digit PIN set on the card.
             * @example 1234
             */
            pin: string;
            /**
             * @description Encrypted private key blob read from the NFC card (base64 string).
             * @example BASE64_ENCRYPTED_PRIVATE_KEY_FROM_CARD==
             */
            encryptedPrivateKeyFromCard: string;
        };
        TransactionResponseDto: {
            /** @description Transaction ID */
            id: number;
            /**
             * @description Transaction kind
             * @enum {string}
             */
            type: "MINT" | "PURCHASE";
            /** @description Transaction amount */
            amount: number;
            /** @description Description */
            description?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /** @description Source account ID (payer); null when not applicable (e.g. mint) */
            fromAccountId?: Record<string, never> | null;
            /** @description Destination account ID */
            toAccountId?: Record<string, never> | null;
        };
        PurchaseItemDto: {
            /**
             * @description 4-digit PIN set on the card.
             * @example 1234
             */
            pin: string;
            /**
             * @description Encrypted private key blob read from the NFC card (base64 string).
             * @example BASE64_ENCRYPTED_PRIVATE_KEY_FROM_CARD==
             */
            encryptedPrivateKeyFromCard: string;
            /**
             * Format: uuid
             * @description Provider account id (vending machine, cafeteria, etc.) that sells the item.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            providerAccountId: string;
            /**
             * @description Optional purchase description.
             * @example Cafeteria lunch
             */
            description?: string;
            /**
             * @description Item ids (UUIDs) to purchase
             * @example [
             *       "3fa85f64-5717-4562-b3fc-2c963f66afa6"
             *     ]
             */
            items: Record<string, never>[][];
        };
        PurchaseItemResponseDto: {
            /** @description Created purchase transaction id */
            transactionId: number;
            /**
             * @description Remaining stock per item id after the purchase (when stock is tracked).
             * @example {
             *       "3fa85f64-5717-4562-b3fc-2c963f66afa6": 9
             *     }
             */
            remainingAmount: {
                [key: string]: number;
            };
        };
        CreateAccountDto: {
            /**
             * Format: uuid
             * @description User id.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            userId: string;
        };
        CreateAccountResponseDto: {
            /** @description User ID */
            id: string;
            /** @description User display name */
            name: string;
            /** @description NFC card UID assigned to the account */
            nfcCardUid: string;
            /** @description Account public key (hex) */
            publicKeyHex: string;
            /** @description 4-digit PIN for the NFC card */
            pin: string;
            /** @description Encrypted private key for programming onto the card (one-time delivery). */
            encryptedPrivateKeyForCard: string;
        };
        AccountListOwnerDto: {
            /** Format: uuid */
            id: string;
            name: string;
            userName: string;
            /** @enum {string} */
            type: "user" | "provider" | "admin";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ListAccountItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** @description NFC card UID when assigned. */
            nfcCardUid?: Record<string, never> | null;
            publicKeyHex: string;
            /** @description Account balance. */
            balance: number;
            isLocked: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description The user that owns this account. */
            owner: components["schemas"]["AccountListOwnerDto"];
        };
        ListAccountsResponseDto: {
            accounts: components["schemas"]["ListAccountItemDto"][];
            /** @description Total rows matching the filters (ignoring limit/offset). */
            total: number;
        };
        CreateProviderItemDto: {
            /** @example Soda can */
            name: string;
            /** @example 330ml soda */
            description: string;
            /**
             * @description Price in currency units.
             * @example 1.5
             */
            value: number;
            /**
             * @description If omitted/null, stock is not tracked (unlimited).
             * @example 10
             */
            amount?: number | null;
        };
        ItemResponseDto: {
            /**
             * Format: uuid
             * @description Item ID
             */
            id: string;
            /** @description Display name */
            name: string;
            /** @description Description */
            description: string;
            /** @description Unit value */
            value: number;
            /** @description Stock amount; null means unlimited / not tracked */
            amount: number | null;
            /**
             * Format: uuid
             * @description Owning item-provider ID
             */
            providerId: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
        MintDto: {
            /**
             * Format: uuid
             * @description Admin user account id.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            adminUserAccountId: string;
            /**
             * Format: uuid
             * @description Target account id.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            accountId: string;
            /**
             * @description Amount to mint.
             * @example 10
             */
            amount: number;
            /**
             * @description Optional mint description.
             * @example Initial top-up
             */
            description?: string;
        };
        MintResponseDto: {
            /**
             * @description Account balance after mint (decimal string).
             * @example 100.00
             */
            balance: string;
        };
        LoginDto: {
            /**
             * @description User username (letters, digits, - _ + only; no spaces)
             * @example alice_2
             */
            userName: string;
            /**
             * @description Account password for API login (Distinct from the generated card PIN).
             * @example a-long-random-secret
             */
            password: string;
        };
        LoginResponseDto: {
            /**
             * @description JWT token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwidXNlclR5cGUiOiJ1c2VyIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
             */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Greeting string */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UsersController_listUsers_v1: {
        parameters: {
            query?: {
                /** @description Return only users of this type. */
                type?: "user" | "provider" | "admin";
                /** @description Case-insensitive substring match on display name or login name (userName). */
                search?: string;
                /** @description Page size (default 50, max 100). */
                limit?: number;
                /** @description Number of rows to skip (pagination). */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponseDto"];
                };
            };
        };
    };
    UsersController_createUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponseDto"];
                };
            };
        };
    };
    UsersController_getUser_v1: {
        parameters: {
            query?: {
                /** @description When true, includes each account id, balance, lock state, public key, and NFC UID (no secrets). */
                includeAccounts?: boolean;
            };
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserResponseDto"];
                };
            };
        };
    };
    UsersController_updateUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequestDto"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateUserResponseDto"];
                };
            };
        };
    };
    UsersController_getCurrentUser_v1: {
        parameters: {
            query?: {
                /** @description When true, includes each account id, balance, lock state, public key, and NFC UID (no secrets). */
                includeAccounts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserResponseDto"];
                };
            };
        };
    };
    ApiTokensController_createApiToken_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestTokenDto"];
            };
        };
        responses: {
            /** @description Token issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestTokenResponseDto"];
                };
            };
        };
    };
    ItemProvidersController_createItemProvider_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemProviderDto"];
            };
        };
        responses: {
            /** @description Item provider created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemProviderResponseDto"];
                };
            };
        };
    };
    TransactionsController_transfer_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferDto"];
            };
        };
        responses: {
            /** @description Transaction created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
        };
    };
    TransactionsController_purchaseItem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseItemDto"];
            };
        };
        responses: {
            /** @description Purchase completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseItemResponseDto"];
                };
            };
        };
    };
    AccountsController_listAccounts_v1: {
        parameters: {
            query?: {
                /** @description Return only accounts owned by this user. */
                userId?: string;
                /** @description Return only accounts whose owner has this user type. */
                ownerType?: "user" | "provider" | "admin";
                /** @description Return only locked (true) or unlocked (false) accounts. */
                isLocked?: boolean;
                /** @description Case-insensitive substring match on NFC card UID, owner display name, or owner login name (userName). */
                search?: string;
                /** @description Page size (default 50, max 100). */
                limit?: number;
                /** @description Number of rows to skip (pagination). */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAccountsResponseDto"];
                };
            };
        };
    };
    AccountsController_createAccount_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountDto"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAccountResponseDto"];
                };
            };
        };
    };
    AccountsController_getAccountTransactions_v1: {
        parameters: {
            query?: {
                /** @description How many transactions to return (default 10, max 100). */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Account ID */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"][];
                };
            };
            /** @description Caller is not the account owner or an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ItemsController_listProviderItems_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider ID */
                providerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponseDto"][];
                };
            };
        };
    };
    ItemsController_createProviderItem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider ID */
                providerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderItemDto"];
            };
        };
        responses: {
            /** @description Item created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponseDto"];
                };
            };
        };
    };
    ItemsController_getProviderItem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider ID */
                providerId: string;
                /** @description Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponseDto"];
                };
            };
        };
    };
    AdminController_mint_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MintDto"];
            };
        };
        responses: {
            /** @description Mint applied */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
